<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Testcontainers.PostgreSql" />
    <ProjectReference Include="..\..\..\src\Infrastructure\ArturRios.Fortuna.Data\ArturRios.Fortuna.Data.csproj" />
  </ItemGroup>

</Project>
