<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="ArturRios.Data.PostgreSql" Version="3.0.1" />
    <PackageVersion Include="ArturRios.Data.Relational.Core" Version="4.0.0" />
    <PackageVersion Include="ArturRios.Mediator" Version="1.0.3" />
    <PackageVersion Include="ArturRios.Util" Version="1.5.0" />
    <PackageVersion Include="ArturRios.Util.Test" Version="2.2.0" />
    <PackageVersion Include="ArturRios.Util.WebApi" Version="3.2.0" />
  </ItemGroup>
  <ItemGroup>
    <PackageVersion Include="EFCore.NamingConventions" Version="10.0.1" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore" Version="10.0.11" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Abstractions" Version="10.0.11" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Analyzers" Version="10.0.11" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.11" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Relational" Version="10.0.11" />
    <PackageVersion Include="Microsoft.AspNetCore.Mvc.Testing" Version="10.0.11" />
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.11" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.11" />
  </ItemGroup>
  <ItemGroup>
    <PackageVersion Include="AWSSDK.S3" Version="4.0.14" />
    <PackageVersion Include="FluentValidation" Version="12.1.1" />
    <PackageVersion Include="Serilog" Version="4.4.0" />
    <PackageVersion Include="Serilog.AspNetCore" Version="10.0.0" />
    <PackageVersion Include="Serilog.Sinks.Map" Version="2.0.0" />
    <PackageVersion Include="Swashbuckle.AspNetCore" Version="10.2.3" />
  </ItemGroup>
  <ItemGroup>
    <PackageVersion Include="Bogus" Version="35.6.5" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.9.0" />
    <PackageVersion Include="Moq" Version="4.20.72" />
    <PackageVersion Include="SSH.NET" Version="2026.0.0" />
    <PackageVersion Include="Testcontainers.PostgreSql" Version="4.14.0" />
    <PackageVersion Include="coverlet.collector" Version="10.0.1" />
    <PackageVersion Include="xunit" Version="2.9.3" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="3.1.5" />
  </ItemGroup>
</Project>
