// <auto-generated />
using System;
using ArturRios.Fortuna.Data.Configuration;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ArturRios.Fortuna.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260905135613_MaterializeRecurringOccurrences")]
    partial class MaterializeRecurringOccurrences
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("fortuna")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ArturRios.Fortuna.Domain.Accounts.FinancialAccount", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<short>("AccountType")
                        .HasColumnType("smallint")
                        .HasColumnName("account_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("CurrencyId")
                        .HasColumnType("bigint")
                        .HasColumnName("currency_id");

                    b.Property<Guid?>("DeletionCascadeId")
                        .HasColumnType("uuid")
                        .HasColumnName("deletion_cascade_id");

                    b.Property<string>("Institution")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("institution");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("normalized_name");

                    b.Property<decimal>("OpeningBalance")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("opening_balance");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uuid")
                        .HasColumnName("public_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_financial_account");

                    b.HasIndex("CurrencyId")
                        .HasDatabaseName("ix_financial_account_currency_id");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("ix_financial_account_public_id");

                    b.HasIndex("UserId", "IsDeleted")
                        .HasDatabaseName("ix_financial_account_user_id_is_deleted");

                    b.HasIndex("UserId", "NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("ux_financial_account_user_normalized_name_live")
                        .HasFilter("NOT is_deleted");

                    b.ToTable("financial_account", "fortuna", t =>
                        {
                            t.HasCheckConstraint("ck_financial_account_deletion_state", "(is_deleted AND deletion_cascade_id IS NOT NULL) OR (NOT is_deleted AND deletion_cascade_id IS NULL)");

                            t.HasCheckConstraint("ck_financial_account_type", "account_type BETWEEN 1 AND 4");
                        });
                });

            modelBuilder.Entity("ArturRios.Fortuna.Domain.Auditing.AuditEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<Guid?>("EntityPublicId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_public_id");

                    b.Property<string>("EntityType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entity_type");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("operation");

                    b.Property<short>("Outcome")
                        .HasColumnType("smallint")
                        .HasColumnName("outcome");

                    b.Property<string>("Reason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("reason");

                    b.HasKey("Id")
                        .HasName("pk_audit_entry");

                    b.HasIndex("ActorUserId")
                        .HasDatabaseName("ix_audit_entry_actor_user_id");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("ix_audit_entry_occurred_at");

                    b.ToTable("audit_entry", "fortuna");
                });

            modelBuilder.Entity("ArturRios.Fortuna.Domain.Cards.CreditCard", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<short>("ClosingDay")
                        .HasColumnType("smallint")
                        .HasColumnName("closing_day");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("CreditLimit")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("credit_limit");

                    b.Property<long>("CurrencyId")
                        .HasColumnType("bigint")
                        .HasColumnName("currency_id");

                    b.Property<Guid?>("DeletionCascadeId")
                        .HasColumnType("uuid")
                        .HasColumnName("deletion_cascade_id");

                    b.Property<short>("DueDay")
                        .HasColumnType("smallint")
                        .HasColumnName("due_day");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("Issuer")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("issuer");

                    b.Property<string>("LastFourDigits")
                        .HasColumnType("char(4)")
                        .HasColumnName("last_four_digits");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("normalized_name");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uuid")
                        .HasColumnName("public_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_credit_card");

                    b.HasIndex("CurrencyId")
                        .HasDatabaseName("ix_credit_card_currency_id");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("ix_credit_card_public_id");

                    b.HasIndex("UserId", "IsDeleted")
                        .HasDatabaseName("ix_credit_card_user_id_is_deleted");

                    b.HasIndex("UserId", "NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("ux_credit_card_user_normalized_name_live")
                        .HasFilter("NOT is_deleted");

                    b.ToTable("credit_card", "fortuna", t =>
                        {
                            t.HasCheckConstraint("ck_credit_card_closing_day", "closing_day BETWEEN 1 AND 31");

                            t.HasCheckConstraint("ck_credit_card_deletion_state", "(is_deleted AND deletion_cascade_id IS NOT NULL) OR (NOT is_deleted AND deletion_cascade_id IS NULL)");

                            t.HasCheckConstraint("ck_credit_card_due_day", "due_day BETWEEN 1 AND 31");

                            t.HasCheckConstraint("ck_credit_card_last_four_digits", "last_four_digits IS NULL OR last_four_digits ~ '^[0-9]{4}$'");

                            t.HasCheckConstraint("ck_credit_card_limit", "credit_limit > 0");
                        });
                });

            modelBuilder.Entity("ArturRios.Fortuna.Domain.Cards.CreditCardStatement", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("AmountDue")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("amount_due");

                    b.Property<DateOnly>("ClosingDate")
                        .HasColumnType("date")
                        .HasColumnName("closing_date");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("CreditCardId")
                        .HasColumnType("bigint")
                        .HasColumnName("credit_card_id");

                    b.Property<Guid?>("DeletionCascadeId")
                        .HasColumnType("uuid")
                        .HasColumnName("deletion_cascade_id");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date")
                        .HasColumnName("due_date");

                    b.Property<decimal>("ForeignTaxTotal")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("foreign_tax_total");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<decimal>("OtherEntries")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("other_entries");

                    b.Property<decimal>("PaymentsReceived")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("payments_received");

                    b.Property<DateOnly>("PeriodEnd")
                        .HasColumnType("date")
                        .HasColumnName("period_end");

                    b.Property<DateOnly>("PeriodStart")
                        .HasColumnType("date")
                        .HasColumnName("period_start");

                    b.Property<decimal>("PreviousBalance")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("previous_balance");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uuid")
                        .HasColumnName("public_id");

                    b.Property<decimal>("PurchaseTotal")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("purchase_total");

                    b.Property<long?>("SettlementTransactionId")
                        .HasColumnType("bigint")
                        .HasColumnName("settlement_transaction_id");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_credit_card_statement");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("ix_credit_card_statement_public_id");

                    b.HasIndex("SettlementTransactionId")
                        .HasDatabaseName("ix_credit_card_statement_settlement_transaction_id");

                    b.HasIndex("CreditCardId", "Status")
                        .HasDatabaseName("ix_credit_card_statement_credit_card_id_status");

                    b.HasIndex("CreditCardId", "PeriodStart", "PeriodEnd")
                        .IsUnique()
                        .HasDatabaseName("ux_credit_card_statement_card_period");

                    b.ToTable("credit_card_statement", "fortuna", t =>
                        {
                            t.HasCheckConstraint("ck_credit_card_statement_deletion_state", "(is_deleted AND deletion_cascade_id IS NOT NULL) OR (NOT is_deleted AND deletion_cascade_id IS NULL)");

                            t.HasCheckConstraint("ck_credit_card_statement_period", "period_start <= period_end AND closing_date = period_end AND due_date > closing_date");

                            t.HasCheckConstraint("ck_credit_card_statement_status", "status BETWEEN 1 AND 3");
                        });
                });

            modelBuilder.Entity("ArturRios.Fortuna.Domain.Classification.Category", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("DeletionCascadeId")
                        .HasColumnType("uuid")
                        .HasColumnName("deletion_cascade_id");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("normalized_name");

                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint")
                        .HasColumnName("parent_id");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uuid")
                        .HasColumnName("public_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_category");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_category_parent_id");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("ix_category_public_id");

                    b.HasIndex("UserId", "IsDeleted")
                        .HasDatabaseName("ix_category_user_id_is_deleted");

                    b.HasIndex("UserId", "NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("ix_category_user_id_normalized_name")
                        .HasFilter("parent_id IS NULL AND NOT is_deleted");

                    b.HasIndex("UserId", "ParentId", "NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("ix_category_user_id_parent_id_normalized_name")
                        .HasFilter("parent_id IS NOT NULL AND NOT is_deleted");

                    b.ToTable("category", "fortuna", t =>
                        {
                            t.HasCheckConstraint("ck_category_deletion_state", "(is_deleted AND deletion_cascade_id IS NOT NULL) OR (NOT is_deleted AND deletion_cascade_id IS NULL)");
                        });
                });

            modelBuilder.Entity("ArturRios.Fortuna.Domain.Classification.Counterparty", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("DeletionCascadeId")
                        .HasColumnType("uuid")
                        .HasColumnName("deletion_cascade_id");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("normalized_name");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uuid")
                        .HasColumnName("public_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_counterparty");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("ix_counterparty_public_id");

                    b.HasIndex("UserId", "IsDeleted")
                        .HasDatabaseName("ix_counterparty_user_id_is_deleted");

                    b.HasIndex("UserId", "NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("ix_counterparty_user_id_normalized_name")
                        .HasFilter("NOT is_deleted");

                    b.ToTable("counterparty", "fortuna", t =>
                        {
                            t.HasCheckConstraint("ck_counterparty_deletion_state", "(is_deleted AND deletion_cascade_id IS NOT NULL) OR (NOT is_deleted AND deletion_cascade_id IS NULL)");
                        });
                });

            modelBuilder.Entity("ArturRios.Fortuna.Domain.Classification.Tag", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("DeletionCascadeId")
                        .HasColumnType("uuid")
                        .HasColumnName("deletion_cascade_id");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("normalized_name");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uuid")
                        .HasColumnName("public_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_tag");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("ix_tag_public_id");

                    b.HasIndex("UserId", "IsDeleted")
                        .HasDatabaseName("ix_tag_user_id_is_deleted");

                    b.HasIndex("UserId", "NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("ix_tag_user_id_normalized_name")
                        .HasFilter("NOT is_deleted");

                    b.ToTable("tag", "fortuna", t =>
                        {
                            t.HasCheckConstraint("ck_tag_deletion_state", "(is_deleted AND deletion_cascade_id IS NOT NULL) OR (NOT is_deleted AND deletion_cascade_id IS NULL)");
                        });
                });

            modelBuilder.Entity("ArturRios.Fortuna.Domain.Currencies.Currency", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("char(3)")
                        .HasColumnName("code");

                    b.Property<short>("MinorUnitDigits")
                        .HasColumnType("smallint")
                        .HasColumnName("minor_unit_digits");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_currency");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_currency_code");

                    b.ToTable("currency", "fortuna");
                });

            modelBuilder.Entity("ArturRios.Fortuna.Domain.Currencies.ExchangeRate", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("BaseCurrencyId")
                        .HasColumnType("bigint")
                        .HasColumnName("base_currency_id");

                    b.Property<long>("QuoteCurrencyId")
                        .HasColumnType("bigint")
                        .HasColumnName("quote_currency_id");

                    b.Property<decimal>("Rate")
                        .HasPrecision(19, 8)
                        .HasColumnType("numeric(19,8)")
                        .HasColumnName("rate");

                    b.Property<DateOnly>("RateDate")
                        .HasColumnType("date")
                        .HasColumnName("rate_date");

                    b.Property<short>("Source")
                        .HasColumnType("smallint")
                        .HasColumnName("source");

                    b.HasKey("Id")
                        .HasName("pk_exchange_rate");

                    b.HasIndex("QuoteCurrencyId")
                        .HasDatabaseName("ix_exchange_rate_quote_currency_id");

                    b.HasIndex("BaseCurrencyId", "QuoteCurrencyId", "RateDate", "Source")
                        .IsUnique()
                        .HasDatabaseName("ix_exchange_rate_base_currency_id_quote_currency_id_rate_date_");

                    b.ToTable("exchange_rate", "fortuna", t =>
                        {
                            t.HasCheckConstraint("ck_exchange_rate_distinct_currency", "base_currency_id <> quote_currency_id");

                            t.HasCheckConstraint("ck_exchange_rate_positive", "rate > 0");
                        });
                });

            modelBuilder.Entity("ArturRios.Fortuna.Domain.Investments.Investment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("CurrencyId")
                        .HasColumnType("bigint")
                        .HasColumnName("currency_id");

                    b.Property<Guid?>("DeletionCascadeId")
                        .HasColumnType("uuid")
                        .HasColumnName("deletion_cascade_id");

                    b.Property<string>("Institution")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("institution");

                    b.Property<string>("Instrument")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("instrument");

                    b.Property<short>("InvestmentType")
                        .HasColumnType("smallint")
                        .HasColumnName("investment_type");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("NormalizedInstrument")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("normalized_instrument");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uuid")
                        .HasColumnName("public_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_investment");

                    b.HasIndex("CurrencyId")
                        .HasDatabaseName("ix_investment_currency_id");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("ix_investment_public_id");

                    b.HasIndex("UserId", "IsDeleted")
                        .HasDatabaseName("ix_investment_user_id_is_deleted");

                    b.HasIndex("UserId", "NormalizedInstrument")
                        .IsUnique()
                        .HasDatabaseName("ux_investment_user_normalized_instrument_live")
                        .HasFilter("NOT is_deleted");

                    b.ToTable("investment", "fortuna", t =>
                        {
                            t.HasCheckConstraint("ck_investment_deletion_state", "(is_deleted AND deletion_cascade_id IS NOT NULL) OR (NOT is_deleted AND deletion_cascade_id IS NULL)");

                            t.HasCheckConstraint("ck_investment_type", "investment_type BETWEEN 1 AND 4");
                        });
                });

            modelBuilder.Entity("ArturRios.Fortuna.Domain.Investments.InvestmentMovement", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("amount");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("DeletionCascadeId")
                        .HasColumnType("uuid")
                        .HasColumnName("deletion_cascade_id");

                    b.Property<long>("InvestmentId")
                        .HasColumnType("bigint")
                        .HasColumnName("investment_id");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<short>("MovementType")
                        .HasColumnType("smallint")
                        .HasColumnName("movement_type");

                    b.Property<DateOnly>("OccurredOn")
                        .HasColumnType("date")
                        .HasColumnName("occurred_on");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uuid")
                        .HasColumnName("public_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_investment_movement");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("ix_investment_movement_public_id");

                    b.HasIndex("InvestmentId", "IsDeleted", "OccurredOn")
                        .HasDatabaseName("ix_investment_movement_investment_id_is_deleted_occurred_on");

                    b.ToTable("investment_movement", "fortuna", t =>
                        {
                            t.HasCheckConstraint("ck_investment_movement_amount", "amount > 0");

                            t.HasCheckConstraint("ck_investment_movement_deletion_state", "(is_deleted AND deletion_cascade_id IS NOT NULL) OR (NOT is_deleted AND deletion_cascade_id IS NULL)");

                            t.HasCheckConstraint("ck_investment_movement_type", "movement_type BETWEEN 1 AND 4");
                        });
                });

            modelBuilder.Entity("ArturRios.Fortuna.Domain.Investments.InvestmentValuation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("DeletionCascadeId")
                        .HasColumnType("uuid")
                        .HasColumnName("deletion_cascade_id");

                    b.Property<long>("InvestmentId")
                        .HasColumnType("bigint")
                        .HasColumnName("investment_id");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uuid")
                        .HasColumnName("public_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<decimal>("Value")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("value");

                    b.Property<DateOnly>("ValuedOn")
                        .HasColumnType("date")
                        .HasColumnName("valued_on");

                    b.HasKey("Id")
                        .HasName("pk_investment_valuation");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("ix_investment_valuation_public_id");

                    b.HasIndex("InvestmentId", "ValuedOn")
                        .IsUnique()
                        .HasDatabaseName("ux_investment_valuation_investment_valued_on_live")
                        .HasFilter("NOT is_deleted");

                    b.HasIndex("InvestmentId", "IsDeleted", "ValuedOn")
                        .HasDatabaseName("ix_investment_valuation_investment_id_is_deleted_valued_on");

                    b.ToTable("investment_valuation", "fortuna", t =>
                        {
                            t.HasCheckConstraint("ck_investment_valuation_deletion_state", "(is_deleted AND deletion_cascade_id IS NOT NULL) OR (NOT is_deleted AND deletion_cascade_id IS NULL)");
                        });
                });

            modelBuilder.Entity("ArturRios.Fortuna.Domain.Jobs.BackgroundJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("correlation_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("failure_reason");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("idempotency_key");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<short>("State")
                        .HasColumnType("smallint")
                        .HasColumnName("state");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_background_job");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ix_background_job_idempotency_key");

                    b.HasIndex("State")
                        .HasDatabaseName("ix_background_job_state");

                    b.ToTable("background_job", "fortuna");
                });

            modelBuilder.Entity("ArturRios.Fortuna.Domain.Transactions.FinancialTransaction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("amount");

                    b.Property<decimal?>("AppliedRate")
                        .HasPrecision(19, 8)
                        .HasColumnType("numeric(19,8)")
                        .HasColumnName("applied_rate");

                    b.Property<long>("CategoryId")
                        .HasColumnType("bigint")
                        .HasColumnName("category_id");

                    b.Property<long?>("CounterpartyId")
                        .HasColumnType("bigint")
                        .HasColumnName("counterparty_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long?>("CreditCardId")
                        .HasColumnType("bigint")
                        .HasColumnName("credit_card_id");

                    b.Property<long>("CurrencyId")
                        .HasColumnType("bigint")
                        .HasColumnName("currency_id");

                    b.Property<Guid?>("DeletionCascadeId")
                        .HasColumnType("uuid")
                        .HasColumnName("deletion_cascade_id");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<short>("Direction")
                        .HasColumnType("smallint")
                        .HasColumnName("direction");

                    b.Property<long?>("FinancialAccountId")
                        .HasColumnType("bigint")
                        .HasColumnName("financial_account_id");

                    b.Property<short?>("InstallmentNumber")
                        .HasColumnType("smallint")
                        .HasColumnName("installment_number");

                    b.Property<long?>("InstallmentPlanId")
                        .HasColumnType("bigint")
                        .HasColumnName("installment_plan_id");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsLateArriving")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_late_arriving");

                    b.Property<bool>("IsManuallyCorrected")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_manually_corrected");

                    b.Property<bool>("IsPossibleDuplicate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_possible_duplicate");

                    b.Property<bool>("IsReconciled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_reconciled");

                    b.Property<DateOnly>("OccurredOn")
                        .HasColumnType("date")
                        .HasColumnName("occurred_on");

                    b.Property<decimal?>("OriginalAmount")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("original_amount");

                    b.Property<long?>("OriginalCurrencyId")
                        .HasColumnType("bigint")
                        .HasColumnName("original_currency_id");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uuid")
                        .HasColumnName("public_id");

                    b.Property<DateOnly?>("RateDate")
                        .HasColumnType("date")
                        .HasColumnName("rate_date");

                    b.Property<long?>("RecurringTransactionId")
                        .HasColumnType("bigint")
                        .HasColumnName("recurring_transaction_id");

                    b.Property<short>("SourceType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1)
                        .HasColumnName("source_type");

                    b.Property<long?>("StatementId")
                        .HasColumnType("bigint")
                        .HasColumnName("statement_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_financial_transaction");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_financial_transaction_category_id");

                    b.HasIndex("CounterpartyId")
                        .HasDatabaseName("ix_financial_transaction_counterparty_id");

                    b.HasIndex("CurrencyId")
                        .HasDatabaseName("ix_financial_transaction_currency_id");

                    b.HasIndex("OriginalCurrencyId")
                        .HasDatabaseName("ix_financial_transaction_original_currency_id");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("ix_financial_transaction_public_id");

                    b.HasIndex("StatementId")
                        .HasDatabaseName("ix_financial_transaction_statement_id");

                    b.HasIndex("InstallmentPlanId", "InstallmentNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_financial_transaction_installment_plan_id_installment_number");

                    b.HasIndex("RecurringTransactionId", "OccurredOn")
                        .IsUnique()
                        .HasDatabaseName("ix_financial_transaction_recurring_transaction_id_occurred_on");

                    b.HasIndex("UserId", "IsDeleted")
                        .HasDatabaseName("ix_financial_transaction_user_id_is_deleted");

                    b.HasIndex("CreditCardId", "IsDeleted", "OccurredOn")
                        .HasDatabaseName("ix_financial_transaction_credit_card_id_is_deleted_occurred_on");

                    b.HasIndex("FinancialAccountId", "IsDeleted", "OccurredOn")
                        .HasDatabaseName("ix_financial_transaction_financial_account_id_is_deleted_occur");

                    b.ToTable("financial_transaction", "fortuna", t =>
                        {
                            t.HasCheckConstraint("ck_financial_transaction_amount", "amount > 0");

                            t.HasCheckConstraint("ck_financial_transaction_deletion_state", "(is_deleted AND deletion_cascade_id IS NOT NULL) OR (NOT is_deleted AND deletion_cascade_id IS NULL)");

                            t.HasCheckConstraint("ck_financial_transaction_direction", "direction BETWEEN 1 AND 2");

                            t.HasCheckConstraint("ck_financial_transaction_foreign_currency", "(original_amount IS NULL AND original_currency_id IS NULL AND applied_rate IS NULL AND rate_date IS NULL) OR (original_amount > 0 AND original_currency_id IS NOT NULL AND applied_rate > 0 AND rate_date IS NOT NULL)");

                            t.HasCheckConstraint("ck_financial_transaction_installment", "(installment_plan_id IS NULL AND installment_number IS NULL) OR (installment_plan_id IS NOT NULL AND installment_number >= 1)");

                            t.HasCheckConstraint("ck_financial_transaction_source_type", "source_type BETWEEN 1 AND 4");

                            t.HasCheckConstraint("ck_financial_transaction_target", "(financial_account_id IS NOT NULL AND credit_card_id IS NULL) OR (financial_account_id IS NULL AND credit_card_id IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("ArturRios.Fortuna.Domain.Transactions.InstallmentPlan", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("CreditCardId")
                        .HasColumnType("bigint")
                        .HasColumnName("credit_card_id");

                    b.Property<Guid?>("DeletionCascadeId")
                        .HasColumnType("uuid")
                        .HasColumnName("deletion_cascade_id");

                    b.Property<short>("InstallmentCount")
                        .HasColumnType("smallint")
                        .HasColumnName("installment_count");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uuid")
                        .HasColumnName("public_id");

                    b.Property<DateOnly>("PurchasedOn")
                        .HasColumnType("date")
                        .HasColumnName("purchased_on");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("total_amount");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_installment_plan");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("ix_installment_plan_public_id");

                    b.HasIndex("CreditCardId", "IsDeleted")
                        .HasDatabaseName("ix_installment_plan_credit_card_id_is_deleted");

                    b.ToTable("installment_plan", "fortuna", t =>
                        {
                            t.HasCheckConstraint("ck_installment_plan_count", "installment_count >= 2");

                            t.HasCheckConstraint("ck_installment_plan_deletion_state", "(is_deleted AND deletion_cascade_id IS NOT NULL) OR (NOT is_deleted AND deletion_cascade_id IS NULL)");

                            t.HasCheckConstraint("ck_installment_plan_total_amount", "total_amount > 0");
                        });
                });

            modelBuilder.Entity("ArturRios.Fortuna.Domain.Transactions.RecurringTransaction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("amount");

                    b.Property<long>("CategoryId")
                        .HasColumnType("bigint")
                        .HasColumnName("category_id");

                    b.Property<long?>("CounterpartyId")
                        .HasColumnType("bigint")
                        .HasColumnName("counterparty_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long?>("CreditCardId")
                        .HasColumnType("bigint")
                        .HasColumnName("credit_card_id");

                    b.Property<long>("CurrencyId")
                        .HasColumnType("bigint")
                        .HasColumnName("currency_id");

                    b.Property<Guid?>("DeletionCascadeId")
                        .HasColumnType("uuid")
                        .HasColumnName("deletion_cascade_id");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<short>("Direction")
                        .HasColumnType("smallint")
                        .HasColumnName("direction");

                    b.Property<DateOnly?>("EndsOn")
                        .HasColumnType("date")
                        .HasColumnName("ends_on");

                    b.Property<long?>("FinancialAccountId")
                        .HasColumnType("bigint")
                        .HasColumnName("financial_account_id");

                    b.Property<short>("Frequency")
                        .HasColumnType("smallint")
                        .HasColumnName("frequency");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<DateOnly?>("LastMaterializedOn")
                        .HasColumnType("date")
                        .HasColumnName("last_materialized_on");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uuid")
                        .HasColumnName("public_id");

                    b.Property<DateOnly>("StartsOn")
                        .HasColumnType("date")
                        .HasColumnName("starts_on");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_recurring_transaction");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_recurring_transaction_category_id");

                    b.HasIndex("CounterpartyId")
                        .HasDatabaseName("ix_recurring_transaction_counterparty_id");

                    b.HasIndex("CreditCardId")
                        .HasDatabaseName("ix_recurring_transaction_credit_card_id");

                    b.HasIndex("CurrencyId")
                        .HasDatabaseName("ix_recurring_transaction_currency_id");

                    b.HasIndex("FinancialAccountId")
                        .HasDatabaseName("ix_recurring_transaction_financial_account_id");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("ix_recurring_transaction_public_id");

                    b.HasIndex("UserId", "IsDeleted")
                        .HasDatabaseName("ix_recurring_transaction_user_id_is_deleted");

                    b.ToTable("recurring_transaction", "fortuna", t =>
                        {
                            t.HasCheckConstraint("ck_recurring_transaction_amount", "amount > 0");

                            t.HasCheckConstraint("ck_recurring_transaction_dates", "ends_on IS NULL OR ends_on >= starts_on");

                            t.HasCheckConstraint("ck_recurring_transaction_deletion_state", "(is_deleted AND deletion_cascade_id IS NOT NULL) OR (NOT is_deleted AND deletion_cascade_id IS NULL)");

                            t.HasCheckConstraint("ck_recurring_transaction_direction", "direction BETWEEN 1 AND 2");

                            t.HasCheckConstraint("ck_recurring_transaction_frequency", "frequency BETWEEN 1 AND 4");

                            t.HasCheckConstraint("ck_recurring_transaction_target", "(financial_account_id IS NOT NULL AND credit_card_id IS NULL) OR (financial_account_id IS NULL AND credit_card_id IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("ArturRios.Fortuna.Domain.Transactions.Transfer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal?>("AppliedRate")
                        .HasPrecision(19, 8)
                        .HasColumnType("numeric(19,8)")
                        .HasColumnName("applied_rate");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("DeletionCascadeId")
                        .HasColumnType("uuid")
                        .HasColumnName("deletion_cascade_id");

                    b.Property<long?>("InboundInvestmentMovementId")
                        .HasColumnType("bigint")
                        .HasColumnName("inbound_investment_movement_id");

                    b.Property<long?>("InboundTransactionId")
                        .HasColumnType("bigint")
                        .HasColumnName("inbound_transaction_id");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<long>("OutboundTransactionId")
                        .HasColumnType("bigint")
                        .HasColumnName("outbound_transaction_id");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uuid")
                        .HasColumnName("public_id");

                    b.Property<DateOnly?>("RateDate")
                        .HasColumnType("date")
                        .HasColumnName("rate_date");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_transfer");

                    b.HasIndex("InboundInvestmentMovementId")
                        .IsUnique()
                        .HasDatabaseName("ix_transfer_inbound_investment_movement_id");

                    b.HasIndex("InboundTransactionId")
                        .IsUnique()
                        .HasDatabaseName("ix_transfer_inbound_transaction_id");

                    b.HasIndex("OutboundTransactionId")
                        .IsUnique()
                        .HasDatabaseName("ix_transfer_outbound_transaction_id");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("ix_transfer_public_id");

                    b.ToTable("transfer", "fortuna", t =>
                        {
                            t.HasCheckConstraint("ck_transfer_conversion", "(applied_rate IS NULL AND rate_date IS NULL) OR (applied_rate > 0 AND rate_date IS NOT NULL)");

                            t.HasCheckConstraint("ck_transfer_deletion_state", "(is_deleted AND deletion_cascade_id IS NOT NULL) OR (NOT is_deleted AND deletion_cascade_id IS NULL)");

                            t.HasCheckConstraint("ck_transfer_movements", "(inbound_transaction_id IS NOT NULL AND inbound_investment_movement_id IS NULL AND outbound_transaction_id <> inbound_transaction_id) OR (inbound_transaction_id IS NULL AND inbound_investment_movement_id IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("ArturRios.Fortuna.Domain.Users.LocalAccount", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uuid")
                        .HasColumnName("public_id");

                    b.Property<byte[]>("Salt")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("salt");

                    b.Property<byte[]>("SecretHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("secret_hash");

                    b.Property<short>("StorageMode")
                        .HasColumnType("smallint")
                        .HasColumnName("storage_mode");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_local_account");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_local_account_name");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("ix_local_account_public_id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_local_account_user_id");

                    b.ToTable("local_account", "fortuna");
                });

            modelBuilder.Entity("ArturRios.Fortuna.Domain.Users.RecoveryCode", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<byte[]>("CodeHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("code_hash");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("LocalAccountId")
                        .HasColumnType("bigint")
                        .HasColumnName("local_account_id");

                    b.Property<DateTimeOffset?>("UsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at");

                    b.HasKey("Id")
                        .HasName("pk_recovery_code");

                    b.HasIndex("LocalAccountId", "CodeHash")
                        .IsUnique()
                        .HasDatabaseName("ix_recovery_code_local_account_id_code_hash");

                    b.ToTable("recovery_code", "fortuna");
                });

            modelBuilder.Entity("ArturRios.Fortuna.Domain.Users.UserProfile", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("DeletionCascadeId")
                        .HasColumnType("uuid")
                        .HasColumnName("deletion_cascade_id");

                    b.Property<long>("DisplayCurrencyId")
                        .HasColumnType("bigint")
                        .HasColumnName("display_currency_id");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<string>("ExternalSubject")
                        .HasColumnType("text")
                        .HasColumnName("external_subject");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uuid")
                        .HasColumnName("public_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_user");

                    b.HasIndex("DisplayCurrencyId")
                        .HasDatabaseName("ix_user_display_currency_id");

                    b.HasIndex("ExternalSubject")
                        .IsUnique()
                        .HasDatabaseName("ux_user_external_subject");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_public_id");

                    b.ToTable("user", "fortuna", t =>
                        {
                            t.HasCheckConstraint("ck_user_deletion_state", "(is_deleted AND deletion_cascade_id IS NOT NULL) OR (NOT is_deleted AND deletion_cascade_id IS NULL)");
                        });
                });

            modelBuilder.Entity("FinancialTransactionTag", b =>
                {
                    b.Property<long>("FinancialTransactionId")
                        .HasColumnType("bigint")
                        .HasColumnName("financial_transaction_id");

                    b.Property<long>("TagId")
                        .HasColumnType("bigint")
                        .HasColumnName("tag_id");

                    b.HasKey("FinancialTransactionId", "TagId")
                        .HasName("pk_financial_transaction_tag");

                    b.HasIndex("TagId")
                        .HasDatabaseName("ix_financial_transaction_tag_tag_id");

                    b.ToTable("financial_transaction_tag", "fortuna");
                });

            modelBuilder.Entity("ArturRios.Fortuna.Domain.Accounts.FinancialAccount", b =>
                {
                    b.HasOne("ArturRios.Fortuna.Domain.Currencies.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_financial_account_currency_currency_id");

                    b.HasOne("ArturRios.Fortuna.Domain.Users.UserProfile", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_financial_account_user_profiles_user_id");

                    b.Navigation("Currency");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ArturRios.Fortuna.Domain.Cards.CreditCard", b =>
                {
                    b.HasOne("ArturRios.Fortuna.Domain.Currencies.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_credit_card_currencies_currency_id");

                    b.HasOne("ArturRios.Fortuna.Domain.Users.UserProfile", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_credit_card_user_profiles_user_id");

                    b.Navigation("Currency");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ArturRios.Fortuna.Domain.Cards.CreditCardStatement", b =>
                {
                    b.HasOne("ArturRios.Fortuna.Domain.Cards.CreditCard", "CreditCard")
                        .WithMany()
                        .HasForeignKey("CreditCardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_credit_card_statement_credit_card_credit_card_id");

                    b.HasOne("ArturRios.Fortuna.Domain.Transactions.FinancialTransaction", "SettlementTransaction")
                        .WithMany()
                        .HasForeignKey("SettlementTransactionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_credit_card_statement_financial_transactions_settlement_tra");

                    b.Navigation("CreditCard");

                    b.Navigation("SettlementTransaction");
                });

            modelBuilder.Entity("ArturRios.Fortuna.Domain.Classification.Category", b =>
                {
                    b.HasOne("ArturRios.Fortuna.Domain.Classification.Category", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_category_category_parent_id");

                    b.HasOne("ArturRios.Fortuna.Domain.Users.UserProfile", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_category_user_profiles_user_id");

                    b.Navigation("Parent");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ArturRios.Fortuna.Domain.Classification.Counterparty", b =>
                {
                    b.HasOne("ArturRios.Fortuna.Domain.Users.UserProfile", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_counterparty_user_profiles_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ArturRios.Fortuna.Domain.Classification.Tag", b =>
                {
                    b.HasOne("ArturRios.Fortuna.Domain.Users.UserProfile", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tag_user_profiles_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ArturRios.Fortuna.Domain.Currencies.ExchangeRate", b =>
                {
                    b.HasOne("ArturRios.Fortuna.Domain.Currencies.Currency", "BaseCurrency")
                        .WithMany()
                        .HasForeignKey("BaseCurrencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_exchange_rate_currency_base_currency_id");

                    b.HasOne("ArturRios.Fortuna.Domain.Currencies.Currency", "QuoteCurrency")
                        .WithMany()
                        .HasForeignKey("QuoteCurrencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_exchange_rate_currency_quote_currency_id");

                    b.Navigation("BaseCurrency");

                    b.Navigation("QuoteCurrency");
                });

            modelBuilder.Entity("ArturRios.Fortuna.Domain.Investments.Investment", b =>
                {
                    b.HasOne("ArturRios.Fortuna.Domain.Currencies.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_investment_currency_currency_id");

                    b.HasOne("ArturRios.Fortuna.Domain.Users.UserProfile", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_investment_user_profiles_user_id");

                    b.Navigation("Currency");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ArturRios.Fortuna.Domain.Investments.InvestmentMovement", b =>
                {
                    b.HasOne("ArturRios.Fortuna.Domain.Investments.Investment", "Investment")
                        .WithMany()
                        .HasForeignKey("InvestmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_investment_movement_investment_investment_id");

                    b.Navigation("Investment");
                });

            modelBuilder.Entity("ArturRios.Fortuna.Domain.Investments.InvestmentValuation", b =>
                {
                    b.HasOne("ArturRios.Fortuna.Domain.Investments.Investment", "Investment")
                        .WithMany()
                        .HasForeignKey("InvestmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_investment_valuation_investment_investment_id");

                    b.Navigation("Investment");
                });

            modelBuilder.Entity("ArturRios.Fortuna.Domain.Transactions.FinancialTransaction", b =>
                {
                    b.HasOne("ArturRios.Fortuna.Domain.Classification.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_financial_transaction_category_category_id");

                    b.HasOne("ArturRios.Fortuna.Domain.Classification.Counterparty", "Counterparty")
                        .WithMany()
                        .HasForeignKey("CounterpartyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_financial_transaction_counterparty_counterparty_id");

                    b.HasOne("ArturRios.Fortuna.Domain.Cards.CreditCard", "CreditCard")
                        .WithMany()
                        .HasForeignKey("CreditCardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_financial_transaction_credit_card_credit_card_id");

                    b.HasOne("ArturRios.Fortuna.Domain.Currencies.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_financial_transaction_currency_currency_id");

                    b.HasOne("ArturRios.Fortuna.Domain.Accounts.FinancialAccount", "FinancialAccount")
                        .WithMany()
                        .HasForeignKey("FinancialAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_financial_transaction_financial_account_financial_account_id");

                    b.HasOne("ArturRios.Fortuna.Domain.Transactions.InstallmentPlan", "InstallmentPlan")
                        .WithMany("Installments")
                        .HasForeignKey("InstallmentPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_financial_transaction_installment_plans_installment_plan_id");

                    b.HasOne("ArturRios.Fortuna.Domain.Currencies.Currency", "OriginalCurrency")
                        .WithMany()
                        .HasForeignKey("OriginalCurrencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_financial_transaction_currency_original_currency_id");

                    b.HasOne("ArturRios.Fortuna.Domain.Transactions.RecurringTransaction", "RecurringTransaction")
                        .WithMany()
                        .HasForeignKey("RecurringTransactionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_financial_transaction_recurring_transactions_recurring_tran");

                    b.HasOne("ArturRios.Fortuna.Domain.Cards.CreditCardStatement", "Statement")
                        .WithMany()
                        .HasForeignKey("StatementId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_financial_transaction_credit_card_statement_statement_id");

                    b.HasOne("ArturRios.Fortuna.Domain.Users.UserProfile", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_financial_transaction_user_profiles_user_id");

                    b.Navigation("Category");

                    b.Navigation("Counterparty");

                    b.Navigation("CreditCard");

                    b.Navigation("Currency");

                    b.Navigation("FinancialAccount");

                    b.Navigation("InstallmentPlan");

                    b.Navigation("OriginalCurrency");

                    b.Navigation("RecurringTransaction");

                    b.Navigation("Statement");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ArturRios.Fortuna.Domain.Transactions.InstallmentPlan", b =>
                {
                    b.HasOne("ArturRios.Fortuna.Domain.Cards.CreditCard", "CreditCard")
                        .WithMany()
                        .HasForeignKey("CreditCardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_installment_plan_credit_card_credit_card_id");

                    b.Navigation("CreditCard");
                });

            modelBuilder.Entity("ArturRios.Fortuna.Domain.Transactions.RecurringTransaction", b =>
                {
                    b.HasOne("ArturRios.Fortuna.Domain.Classification.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_recurring_transaction_category_category_id");

                    b.HasOne("ArturRios.Fortuna.Domain.Classification.Counterparty", "Counterparty")
                        .WithMany()
                        .HasForeignKey("CounterpartyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_recurring_transaction_counterparty_counterparty_id");

                    b.HasOne("ArturRios.Fortuna.Domain.Cards.CreditCard", "CreditCard")
                        .WithMany()
                        .HasForeignKey("CreditCardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_recurring_transaction_credit_card_credit_card_id");

                    b.HasOne("ArturRios.Fortuna.Domain.Currencies.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_recurring_transaction_currency_currency_id");

                    b.HasOne("ArturRios.Fortuna.Domain.Accounts.FinancialAccount", "FinancialAccount")
                        .WithMany()
                        .HasForeignKey("FinancialAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_recurring_transaction_financial_account_financial_account_id");

                    b.HasOne("ArturRios.Fortuna.Domain.Users.UserProfile", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_recurring_transaction_user_profiles_user_id");

                    b.Navigation("Category");

                    b.Navigation("Counterparty");

                    b.Navigation("CreditCard");

                    b.Navigation("Currency");

                    b.Navigation("FinancialAccount");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ArturRios.Fortuna.Domain.Transactions.Transfer", b =>
                {
                    b.HasOne("ArturRios.Fortuna.Domain.Investments.InvestmentMovement", "InboundInvestmentMovement")
                        .WithMany()
                        .HasForeignKey("InboundInvestmentMovementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_transfer_investment_movement_inbound_investment_movement_id");

                    b.HasOne("ArturRios.Fortuna.Domain.Transactions.FinancialTransaction", "InboundTransaction")
                        .WithMany()
                        .HasForeignKey("InboundTransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_transfer_financial_transaction_inbound_transaction_id");

                    b.HasOne("ArturRios.Fortuna.Domain.Transactions.FinancialTransaction", "OutboundTransaction")
                        .WithMany()
                        .HasForeignKey("OutboundTransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_transfer_financial_transaction_outbound_transaction_id");

                    b.Navigation("InboundInvestmentMovement");

                    b.Navigation("InboundTransaction");

                    b.Navigation("OutboundTransaction");
                });

            modelBuilder.Entity("ArturRios.Fortuna.Domain.Users.LocalAccount", b =>
                {
                    b.HasOne("ArturRios.Fortuna.Domain.Users.UserProfile", "User")
                        .WithOne()
                        .HasForeignKey("ArturRios.Fortuna.Domain.Users.LocalAccount", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_local_account_user_profiles_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ArturRios.Fortuna.Domain.Users.RecoveryCode", b =>
                {
                    b.HasOne("ArturRios.Fortuna.Domain.Users.LocalAccount", "LocalAccount")
                        .WithMany("RecoveryCodes")
                        .HasForeignKey("LocalAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_recovery_code_local_account_local_account_id");

                    b.Navigation("LocalAccount");
                });

            modelBuilder.Entity("ArturRios.Fortuna.Domain.Users.UserProfile", b =>
                {
                    b.HasOne("ArturRios.Fortuna.Domain.Currencies.Currency", "DisplayCurrency")
                        .WithMany()
                        .HasForeignKey("DisplayCurrencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_user_currency_display_currency_id");

                    b.Navigation("DisplayCurrency");
                });

            modelBuilder.Entity("FinancialTransactionTag", b =>
                {
                    b.HasOne("ArturRios.Fortuna.Domain.Transactions.FinancialTransaction", null)
                        .WithMany()
                        .HasForeignKey("FinancialTransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_financial_transaction_tag_financial_transaction_financial_t");

                    b.HasOne("ArturRios.Fortuna.Domain.Classification.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_financial_transaction_tag_tags_tag_id");
                });

            modelBuilder.Entity("ArturRios.Fortuna.Domain.Transactions.InstallmentPlan", b =>
                {
                    b.Navigation("Installments");
                });

            modelBuilder.Entity("ArturRios.Fortuna.Domain.Users.LocalAccount", b =>
                {
                    b.Navigation("RecoveryCodes");
                });
#pragma warning restore 612, 618
        }
    }
}
