/* Generated by cbindgen. Do not edit by hand. */

#ifndef FORTUNA_CORE_H
#define FORTUNA_CORE_H

#pragma once

/* Regenerate with: cargo build --manifest-path native/fortuna-core/Cargo.toml */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Successful call. Operation functions use HTTP-compatible numeric statuses.
 */
#define FORTUNA_STATUS_OK 200

/**
 * The JSON request or initialization configuration is invalid.
 */
#define FORTUNA_STATUS_BAD_REQUEST 400

/**
 * Authentication is absent, invalid, or expired.
 */
#define FORTUNA_STATUS_UNAUTHORIZED 401

/**
 * The requested resource or disabled local-auth surface is unavailable.
 */
#define FORTUNA_STATUS_NOT_FOUND 404

/**
 * Initialization was requested while the core was already initialized.
 */
#define FORTUNA_STATUS_CONFLICT 409

/**
 * Persistence or another unexpected native-core operation failed.
 */
#define FORTUNA_STATUS_INTERNAL_ERROR 500

/**
 * An operation requiring initialized services was called before initialization.
 */
#define FORTUNA_STATUS_NOT_INITIALIZED 503

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Initialize the native core from a UTF-8 JSON object.
 *
 * Request: `{"databasePath":"/absolute/path/fortuna.db","localAuthEnabled":true,
 * "tokenLifetimeSeconds":3600}`. The database is created and migrated on demand.
 * Concurrent calls are supported; a second initialization returns 409.
 * The response is always library-owned and must be released with `fortuna_string_free`.
 */
int fortuna_initialize(const char *request_json, char **response_json);

/**
 * Shut down the current native core and invalidate all in-memory sessions.
 * The response is library-owned and must be released with `fortuna_string_free`.
 */
int fortuna_shutdown(const char *request_json, char **response_json);

/**
 * Return the native core package version. Initialization is not required.
 * The response is library-owned and must be released with `fortuna_string_free`.
 */
int fortuna_version(const char *request_json, char **response_json);

/**
 * Return 200 when SQLite can be opened, or 503 before initialization.
 * The response is library-owned and must be released with `fortuna_string_free`.
 */
int fortuna_health(const char *request_json, char **response_json);

/**
 * Mirror `POST /api/local-accounts/authenticate` for the native local account.
 *
 * Request body: `{"name":"Local User","secret":"..."}`. The response uses the
 * same `DataOutput<AuthenticateLocalAccountCommandOutput?>` JSON shape as HTTP.
 * The request is copied only into zeroizing memory and is never logged.
 * The response is library-owned and must be released with `fortuna_string_free`.
 */
int fortuna_api_local_accounts_authenticate(const char *request_json, char **response_json);

/**
 * Mirror `GET /api/accounts/{id}` for the authenticated native local account.
 *
 * Transport metadata and route values are carried in one JSON object:
 * `{"token":"...","id":"uuid","includeDeleted":false}`. The response is the
 * HTTP `DataOutput<FinancialAccountOutput?>` shape. Decimal fields are read from
 * SQLite TEXT and emitted as arbitrary-precision JSON numbers without a float conversion.
 * The response is library-owned and must be released with `fortuna_string_free`.
 */
int fortuna_api_accounts_get_by_id(const char *request_json, char **response_json);

/**
 * Release a response returned by any Fortuna native-core function.
 *
 * Passing NULL is a no-op. A non-NULL pointer must be released exactly once by
 * the same loaded library instance; accessing it after this call is invalid.
 *
 * # Safety
 *
 * A non-NULL pointer must have been returned through a response out parameter by
 * this exact loaded library instance and must not have been freed previously.
 */
void fortuna_string_free(char *response_json);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* FORTUNA_CORE_H */
